### ISSUE TITLE
Column access

### ISSUE THREAD

**Issue by mrocklin** [Blosc/castra#1]
We usually don't need all columns at once.  We store them separately but haven't yet provide separate access (though I suspect that this is only a few lines of code)

How do we want to spell these queries?  The typical pandas/bcolz solution seems odd.

```python
>>> c[['col1', 'col2', 'col3']]['2014-01': '2014-02']
```

Thoughts on throwing out getitem syntax for a method?

```python
>>> c.select(start='2014-01', stop='2014-02', columns=['col1', 'col2'])
```

Or we could merge both getitems into one

```python
>>> c['2014-01': '2014-02', ['col1', 'col2', 'col2'])
```

**Comment by esc** [comment]
They all look odd, select still seems the most elegant but is inconsistent to  ``__getitem__``

**Comment by mrocklin** [comment]
We might not want to use getitem until we actually know what we want to do with it.  It's hard to go back once that choice is made.

**Comment by esc** [comment]
Upon further pondering I came to the conclusion, that:

```
>>> c['2014-01': '2014-02', ['col1', 'col2', 'col2'])
```

Is the best since it mimics Numpy 2D access. Providing either a single identifier, an iterable (not a tuple), or a slice should be permitted for both arguments.
